### PR TITLE
Fix a bug of sync last query not right

### LINKED ISSUE #2256: sync last point query not right
**To Reproduce**
1. in sync sender
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-01 00:00:00.000,21.113817)
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-02 00:00:00.000,20.653296)
flush
2. after sync
 in sync sender
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-04 00:00:00.000,24.588139)
flush
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-04T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|24.588139|
+-----------------------------+-----------------------------+---------+
3. after sync
in sync receiver
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-02T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|20.653296|
+-----------------------------+-----------------------------+---------+

**Expected behavior**
in sync receiver
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-04T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|24.588139|
+-----------------------------+-----------------------------+---------+

**Desktop (please complete the following information):**
 - Version 0.11.0

### PR DESCRIPTION
**Pull request by fanhualta**
Closes #2256

### CODE REVIEW

**Review by HTHou — APPROVED** [review]

File: server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java [hunk 1]
```diff
@@ -1835,18 +1836,50 @@ public void loadNewTsFileForSync(TsFileResource newTsFileResource) throws LoadFi
...
+  private void tryToDeleteLastCacheByDevice(PartialPath deviceId) throws WriteProcessException {
+    if (!IoTDBDescriptor.getInstance().getConfig().isLastCacheEnabled()) {
+      return;
+    }
+    try {
+      MNode node = IoTDB.metaManager.getDeviceNode(deviceId);
+
+      for (MNode measurementNode : node.getChildren().values()) {
+        if (measurementNode != null) {
+          TimeValuePair lastPair = ((MeasurementMNode) measurementNode).getCachedLast();
```
Comment (wshao08) [inline server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java:1872]: Hi, calling resetCache() will set cachedLastValuePair to null. So here you can get rid of lastPair and just call resetCache().

**Review by wshao08 — CHANGES_REQUESTED** [review]
One minor issue. Please check

**Review by wshao08 — APPROVED** [review]
